---
title: "Map Plots in R"
description: "Examples of how to plot various maps in R"
format: 
   gfm:
     toc: true
     toc-depth: 2
     code-fold: show
     code-summary: "Hide code"
     preview-mode: raw
editor: source
editor_options: 
  chunk_output_type: console
---

## Overview
Example map plots


### Libraries
```{r warning=FALSE, message=FALSE}
library(here) # directory management
library(tidyverse) # data wrangling
library(ggspatial) # map annotation
library(terra) # spatial data wrangling
library(sf) # spatial data wrangling
library(tigris) # state and county boundaries

# retain tigris downloads
options(tigris_use_cache = TRUE)
```


## Read Poultry Data
```{r}
layers_df <- read_csv(here("local/Poultry_hybrid_FINAL_CSVs/layers_hybrid_FINAL.csv"))

head(layers_df)
dim(layers_df)

# filter to states of interest
layers_st <- layers_df %>%
  filter(State %in% c("OH", "IN"))

```

## Get State Boundaries
```{r}
states_all <- states(cb = TRUE) # all states

# subset to target states
oh_in_states <- subset(states_all, NAME %in% c("Ohio", "Indiana")) # Ohio and Indiana

```

## Get County Boundaries
```{r}
all_counties <- counties(cb = TRUE)

# subset to target states
oh_in_counties <- subset(all_counties, STATE_NAME %in% c("Ohio", "Indiana"))

# subset to target counties
target_counties <- subset(oh_in_counties, NAME %in% c("Jay", "Adams", "Mercer", "Darke"))

# There's an Adams County in Ohio, remove it (we want Adams, IN)
target_counties <- target_counties[!(target_counties$NAME == "Adams" & target_counties$STATE_NAME == "Ohio"), ]
```


## State Level
States with layers as points.
```{r fig.width=15, fig.height=15}
ggplot() +
  geom_sf(data = oh_in_counties, 
          fill = "white", 
          color = "gray80", 
          size = 0.1) +
  geom_sf(data = oh_in_states, 
          fill = "transparent", 
          color = "gray40", 
          linewidth = 0.8) +
  geom_sf(data = target_counties, 
          fill = "steelblue", 
          color = "gray40", 
          linewidth = 0.8) +
  geom_point(data=layers_st,
             aes(POINT_X, POINT_Y, col=category),
             shape=1,
             size=0.5) +
  annotation_scale(location = "br", 
                   width_hint = 0.3, 
                   text_cex = 0.8,
                   pad_x = unit(0.2, "cm"), 
                   pad_y = unit(0.2, "cm")) +
  annotation_north_arrow(location = "br", 
                         which_north = "true",
                         style = north_arrow_fancy_orienteering,
                         height = unit(2.2, "cm"), 
                         width = unit(2.2, "cm"),
                         pad_x = unit(1.0, "cm"), 
                         pad_y = unit(0.5, "cm")) +
  coord_sf(crs = st_crs(4326)) +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "none",
    axis.title.x = element_text(size = 20, face = "bold"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    plot.title = element_text(size = 22, face = "bold", hjust = 0.5)
  ) +
  labs(title = "States of Interest", x = " ", y = " ")

```


## County Level
Filter points to target counties
```{r}
# join state and county FIPS codes to create full FIPS
target_counties$fips <- paste0(target_counties$STATEFP, target_counties$COUNTYFP)

# FIPS needed
target_fips <- unique(target_counties$fips)

# filter layers to target counties
layers_county <- layers_st %>%
  filter(fips %in% target_fips)

```


```{r fig.width=15, fig.height=15}
county_map <- ggplot() +
  geom_sf(data = target_counties, 
          fill = "gray80", 
          color = "gray40", 
          linewidth = 0.8) +
  geom_point(data=layers_county,
             aes(POINT_X, POINT_Y, col=category),
             shape=1,
             size=1.5,
             stroke=1) +
  annotation_scale(location = "bl", 
                   width_hint = 0.3, 
                   text_cex = 0.8,
                   pad_x = unit(0.2, "cm"), 
                   pad_y = unit(0.2, "cm")) +
  annotation_north_arrow(location = "bl", 
                         which_north = "true",
                         style = north_arrow_fancy_orienteering,
                         height = unit(2.2, "cm"), 
                         width = unit(2.2, "cm"),
                         pad_x = unit(1.0, "cm"), 
                         pad_y = unit(0.5, "cm")) +
  coord_sf(crs = st_crs(4326)) +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "none",
    axis.title.x = element_text(size = 20, face = "bold"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    plot.title = element_text(size = 22, face = "bold", hjust = 0.5)
  ) +
  labs(title = "Counties of Interest", x = " ", y = " ")

county_map

```



## Save Copy
```{r}
# Image
ggsave(file.path(here("local/maps"), "map_locations.png"),
       plot = county_map, width = 8, height = 6, dpi = 1200)

# PDF
ggsave(file.path(here("local/maps"), "map_locations.pdf"),
       plot = county_map, width = 8, height = 6)

```