---
title: "SciNet HPC Overview"
Description: "SCINet data transfer, interactive R via the command line, batch submissions, and OnDemand"
date: "2026-04-16"
about:
  template: marquee
format: 
   gfm:
     toc: true
     toc-depth: 2
     code-fold: show
     code-summary: "Hide code"
     preview-mode: raw
editor_options: 
  chunk_output_type: console
---  
  
## Linked Resources   
  
#### Access ATLAS  
Link: https://atlas-ood.hpc.msstate.edu/

#### Access CERES  
Link: http://ceres-ood.scinet.usda.gov/

#### Globus File Transfer     
Globus instructions: https://scinet.usda.gov/guides/data/transfer/globus  
Link: https://www.globus.org/  

#### Install R Spatial Packages  
Link: https://github.com/geoepi/sandbox/blob/main/2025-12-09-atlas_spatial_packages.md  

#### Connect GitHub and Atlas   
Link: https://github.com/geoepi/sandbox/blob/main/2025-04-16-git_from_atlas.md   
   
#### SSH Access (Windows PowerShell)   
Link: https://scinet.usda.gov/guides/access/ssh-login  
   
#### SCINet Training  
Link: https://scinet.usda.gov/events
  

## Discussion Topics  
  
### Login and Directories   
1.    Login to OnDemand (try both Atlas and Ceres)  
  A. Use of PIV card now preferred, but ssh from PowerShell possible  
  B. Note: Tabs across top of page to access interactive GUI`s, Files, and terminals.  
2.    `Files` tab: Navigable directory via web interface  
  A. Find, create, and create directories    
  B. `Upload` and `Download` options (click, drag, and drop style)    
  C. Web interface good for smaller data, Globus recommended for big data    
3.    Where to save, keep, and archive data?    
  A. **Home** directory: Very small storage, good for individual software installs    
  B. **Project** directories: Project-specific, look at *disease_ecology*, *hpai_plume*, *fadru_fmd*, etc as examples.    
    i. Same project names used on Ceres, Atlas, and Juno  
    ii. Size determined by P.I.'s, may be increased as needed    
    iii. This is where computational work is performed    
  C. **90daydata** directory: includes a project-specific directory *unlimited* storage, but deleted after 90days of being idle.    
    i. Best place for staging big data prior to prepossessing    
    ii. Pull it into the **Project** directory as needed.    
  D. **Juno** directory: Long-term data archiving.  Typically used when project is complete to create enduring data record.    
  
  
### Globus    
1.    See recoomendations on SCINet here [Scinet: Globus](https://scinet.usda.gov/guides/data/datatransfer)   
2.    Use of ORCID suggested for credentials and authentication.  
3.    Search for Ceres and Atlas in the `Collection` box, use `SCINet-Atlas` and `SCINet-Ceres`  
4.    Open side-by-side windows to view files between HPCs, or between HPCs and your local machine.  
5.    Select files, click `Start ->` arrow button to transfer  
  
## Interactive Sessions  

## Terminal (command line)  
1.    Open terminals  
2.    Navigate and create directories  
3.    Scroll through installed software `module spider`  
4.    Find available R versions `module spider r`  
5.    Choose and R version `module spider r/4.5`  
6.    Load module `module load r/4.5` then open R using `R`  
7.    Install packages.  If asked, reply *yes* to use a new directory.  This will install the package in your **Home** directory.
   
## Submit Batch  
 
  

     

